export const LABELS = {
  MUTE: 'Mute',
  UNMUTE: 'Unmute',
  NEXT: 'Next',
  BACK: 'Back',
  SUBMIT: 'Submit Application',
  PERSONAL_INFO: 'Personal Information',
  EXPERIENCE: 'Experience',
  RESUME: 'Resume',
  REGISTER_TITLE: 'Application Form',
  REGISTER_SUBTITLE: 'Complete your profile in three simple steps',
  STEP_OF: 'Step',
  OF: 'of',
  COMPLETE_SUFFIX: 'Complete',
  PHONE_NUMBER: 'Phone Number',
  STREET_ADDRESS: 'Street Address',
  CITY: 'City',
  STATE: 'State',
  ZIP_CODE: 'ZIP Code',
  PH_PHONE_PLACEHOLDER: 'Enter your phone number',
  PH_STREET_PLACEHOLDER: 'Enter your street address',
  PH_CITY_PLACEHOLDER: 'Enter your city',
  PH_STATE_PLACEHOLDER: 'Enter your state',
  PH_ZIP_PLACEHOLDER: 'Enter your ZIP code',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL_ADDRESS: 'Email Address',
  AGE: 'Age',
  DEGREE: 'Degree',
  PROJECT: 'Project',
  EXPERIENCE_LABEL: 'Experience',
  REVIEW_DETAILS: 'Review your details before submitting',
};
